sudo: required
language: java
services:
- docker
before_install:
- mkdir /tmp/build
- docker pull qcifengineering/redbox-builder
- docker run -v /tmp/build:/build -e "CLONEPATH=https://github.com/the-fascinator/plugin-roles-internal.git"
  qcifengineering/redbox-builder
install: true
script: true
after_success:
- docker run -v /tmp/build:/build -e "SONATYPE_USERNAME=$SONATYPE_USERNAME" -e "SONATYPE_PASSWORD=$SONATYPE_PASSWORD"
  qcifengineering/redbox-builder /bin/bash -c "cd build/src;mvn --settings /m2_repo/travis-settings.xml
  -Dmaven.repo.local=/m2_repo -DskipTests=true deploy"
env:
  global:
  - secure: B6yaOJlvzXMHWD7tnDQgvtIvcdTUmuRqUTjm9Yhvdqizc0hmM1vbyOYJRBX0Bqvy5W2euYccuO6lLMCJITPXuOhc0VHAQo3JFQtGJOkq5FSovfoWcl08D8mH2PM0JxiEguNfB4z8Nzs/0c2+KMaZXpuGe2+wu6TAA2gK9ynpF+XIVWV7uPqiyfQnXz/r4J5viCAbeO9K6k7b9MNVuz9iOzB4KkKKLhpmsQu/2XTOLVRB2EubjCFwtuAdkiA44MREHdcX0oqTcifKL800lZDc6DOrWkASFHTF4SCDtKhHC7HmNTseCJ1iWHa0i8tPh5C0YFaQUmNQvb9mDPfgd/so4yplqZLVUnirRa5WsYzvifZQ6F9M0lG/ciawI1hmIPR+Z3gFhTzFZLWPDTD67gL302W6t7qSYTK0iuX3cZwxliAgh6QYPCi5K3R+Nhwv6BpKKESLMv8L1SUvL9earznRKMxqAWmsBYVsgFnVBHfHUuMJxsqTGZOwdaKMDW+jwC81Zw2D3hYYYaeLVgdsHJ7gSlmNS60PoJR8CBJIZVJ2qFIPn5hhO2iWh9o5d9+5gkB1XGBdIxBDcsD8LlosPCyWT0HvASw0T8LliIvlsa9Cqf50u1uXwe3yf6pCfPTmOBJuULrO4OYSkTEDefjKwSoU6hbVWi8V/YH4x5PSbusg1PQ=
  - secure: hRaxjzpt5gygeIJ9BcKlGo0wFNQaGKEBs/W279yl3KG2E97Mgk/fPWS1dy72elyzNM5kcdiGC2ll8+8hHfN6cRzVE0BMymSvnXPzXN3hThh6/ap3t6Ljed2jl/ndpwJiQ88+rqCjY92t1YILf2S6MfLfwsStkeHl7r6yKEBb9HEqSAoeE30J1XHBTUOFcOuaDFgKnu1FZzOkjXhhHHHnl7aQ1ZpH4pAYsCZ0ZlfpLTrQJrFiuTlsmv4dyN1B3V2L10SVpLmC343Vp7xamVsYqa7eocdkVXoRXYE6sGrAwZrO+npWzsvDyq75td1ZhHkBKjDOGggFdU4lNxQe0khyp9+7MawF/Z0tk5EiqbKeG+HtrCZx9SwIvcPbtokPGFpU74O+C5EX9+SfhDspr9yrb5Y3AdsIwVkuvHErYN+OR4HEwEmO2fyGTX/+jT8M37tMIpX2m02dP14SOdwL05UqJSnCYizNlRBXlPywQmtIDeBRKVEx5/dpJv9Bt4/41QGMYyWcFfdBupXlyieCaGlEGt/X9MUDHzrWb1vwg/YLMm5imq+3AWSfNFDVRCE+63Wn0o37m6i9tLqysaUQy56tGunPtBCI4jLAOK6vcjQ4kY5njGau91Nhb1lEs4Ovm9LD3Fb8AvZbMABGSvNOWYtV5zFopyjfThJteCQrotZFYEU=
notifications:
  webhooks:
    urls:
      - http://dev.redboxresearchdata.com.au/hooks/travis
    on_success: always
    on_failure: never
    on_start: never
